##
## --------------------------------------------------------------------------------
## SPDX-FileCopyrightText: 2025 Martin Jan Köhler
## Johannes Kepler University, Institute for Integrated Circuits.
##
## This file is part of openpdk-pmap 
## (see https://github.com/martinjankoehler/openpdk-pmap).
##
## This program is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program. If not, see <http://www.gnu.org/licenses/>.
## SPDX-License-Identifier: GPL-3.0-or-later
## --------------------------------------------------------------------------------
##
name: "Publish distribution 📦s to PyPI/TestPyPI"

on:
  workflow_call:
  
# NOTE: concurrency settings must be defined in calling workflow!
#       otherwise unexpected cancellations will happen
#   example error: "Canceling since a higher priority waiting request for 'martinjankoehler/klayout-pex-release-v0.1.4-Multi-platform Python/C++ build/test' exists"

jobs:
  publish-test-pypi:
    name: "Publish distribution 📦s to TestPyPI"
    runs-on: ubuntu-latest
    continue-on-error: true

    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing

    steps:
      # NOTE: For now, we don't have any native C++ code deployed as part of the python distribution,
      #       so all platforms create the same wheels/source archives.
      #       Therefore it's sufficient to use the ubuntu download artifact:
      #           python-dist-ubuntu-latest_py3.13
      - name: "Download and merge Python dist artifacts"
        uses: actions/download-artifact@v5
        with:
          #                                      # for multi architectures:
          #--------------------------------------#---------------------------
          pattern: python-dist*    # pattern: python-dist-*
          merge-multiple: true
          path: dist   # destination

      - name: "List dist directory"
        run: find dist
      
      - uses: pypa/gh-action-pypi-publish@release/v1
        # continue-on-error: true   # might fail if we don't bump the version
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
          attestations: false

  publish-production-pypi:
    name: "Publish distribution 📦s to PyPI"
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing

    steps:
      # NOTE: For now, we don't have any native C++ code deployed as part of the python distribution,
      #       so all platforms create the same wheels/source archives.
      #       Therefore it's sufficient to use the ubuntu download artifact:
      #           python-dist-ubuntu-latest_py3.13
      - name: "Download and merge Python dist artifacts"
        uses: actions/download-artifact@v5
        with:
          #                                      # for multi architectures:
          #--------------------------------------#---------------------------
          pattern: python-dist*    # pattern: python-dist-*
          merge-multiple: true
          path: dist   # destination

      - name: "List dist directory"
        run: find dist
      
      - uses: pypa/gh-action-pypi-publish@release/v1
        # continue-on-error: true   # might fail if we don't bump the version
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          repository-url: https://upload.pypi.org/legacy/
          attestations: false


